resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/miguelanrolhor/concourse
    branch: master

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml